version: '3.3'
services:
   frontend:
      build: .
      env_file: ./config/config.env
      ports:
      - '3000:3000'
      networks:
      - storybook-net
      depends_on:
      - mongodb

   mongodb:
      image: mongo 
      ports:
      - 27017:27017
      environment:
      - MONGO_INITDB_DATABASE=storybooks
      networks:
      - storybook-net
      volumes:
      - mongo-data:/data/db

networks:
   storybook-net:

volumes:
   mongo-data:
        
